yarnPath: ".yarn/releases/yarn-berry.cjs"

packageExtensions:
  "@emotion/react@*":
    peerDependencies:
      "@emotion/babel-plugin": "*"
  "next-on-netlify@*":
    dependencies:
      "find-cache-dir": "*"
