packageExtensions:
  "@angular-builders/jest@*":
    peerDependencies:
      rxjs: "*"
  "@chakra-ui/accordion@*":
    peerDependencies:
      framer-motion: "*"
  "@chakra-ui/checkbox@*":
    peerDependencies:
      framer-motion: "*"
  "@chakra-ui/media-query@*":
    peerDependencies:
      "@emotion/react": ">= 11"
      "@emotion/styled": ">= 11"
  "@chakra-ui/skeleton@*":
    peerDependencies:
      "@emotion/react": ">= 11"
      "@emotion/styled": ">= 11"
  "@chakra-ui/switch@*":
    peerDependencies:
      framer-motion: "*"
  "@chakra-ui/system@*":
    peerDependencies:
      "@emotion/react": ">= 11"
      "@emotion/styled": ">= 11"
  "@chakra-ui/transition@*":
    peerDependencies:
      framer-motion: "*"
  "@emotion/react@*":
    peerDependencies:
      "@emotion/babel-plugin": "*"
  jest-preset-angular@*:
    peerDependencies:
      "@angular/compiler-cli": "*"
      tslib: "*"
      zone.js: "*"

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: "@yarnpkg/plugin-workspace-tools"

yarnPath: .yarn/releases/yarn-2.4.2.cjs
