packageExtensions:
  "@emotion/react@*":
    peerDependencies:
      "@emotion/babel-plugin": "*"
  next-on-netlify@*:
    dependencies:
      find-cache-dir: "*"

yarnPath: .yarn/releases/yarn-2.4.0.cjs
